#!/bin/sh
# Created: Mon Mar 11 13:23:26 MYT 2013
if test -d .git; then
  dirs=.
else
  dirs=`ls -d */|sort`
fi
echo -n "`basename $PWD` "
for d in $dirs; do
  GIT_DIR=$d/.git GIT_WORK_TREE=$d git log --no-decorate -1 --oneline
done | sort | sha1sum
